-- Automatically generated with ffi-cdecl.

require("ffi").cdef[[
typedef signed char l_int8;
typedef unsigned char l_uint8;
typedef short l_int16;
typedef unsigned short l_uint16;
typedef int l_int32;
typedef unsigned int l_uint32;
typedef float l_float32;
typedef double l_float64;
typedef int l_ok;
typedef struct Box BOX;
typedef struct Boxa BOXA;
typedef struct Numa NUMA;
typedef struct Pix PIX;
typedef struct Pixa PIXA;
static const unsigned L_NOCOPY = 0;
static const unsigned L_COPY = 1;
static const unsigned L_CLONE = 2;
BOX *boxAdjustSides(BOX *boxd, BOX *boxs, l_int32 delleft, l_int32 delright, l_int32 deltop, l_int32 delbot);
BOX *boxCreate(l_int32 x, l_int32 y, l_int32 w, l_int32 h);
void boxDestroy(BOX **pbox);
l_ok boxGetGeometry(const BOX *box, l_int32 *px, l_int32 *py, l_int32 *pw, l_int32 *ph);
BOX *boxOverlapRegion(BOX *box1, BOX *box2);
l_ok boxaAddBox(BOXA *boxa, BOX *box, l_int32 copyflag);
BOXA *boxaClipToBox(BOXA *boxas, BOX *box);
BOXA *boxaCombineOverlaps(BOXA *boxas, PIXA *pixadb);
BOXA *boxaCreate(l_int32 n);
void boxaDestroy(BOXA **pboxa);
BOX *boxaGetBox(BOXA *boxa, l_int32 index, l_int32 accessflag);
l_ok boxaGetBoxGeometry(BOXA *boxa, l_int32 index, l_int32 *px, l_int32 *py, l_int32 *pw, l_int32 *ph);
l_int32 boxaGetCount(const BOXA *boxa);
NUMA *numaCreateFromFArray(l_float32 *farray, l_int32 size, l_int32 copyflag);
void numaDestroy(NUMA **pna);
l_int32 numaGetCount(NUMA *na);
l_float32 *numaGetFArray(NUMA *na, l_int32 copyflag);
l_ok numaGetIValue(NUMA *na, l_int32 index, l_int32 *pival);
PIX *pixClipRectangle(PIX *pixs, BOX *box, BOX **pboxc);
PIX *pixClone(PIX *pixs);
BOXA *pixConnCompBB(PIX *pixs, l_int32 connectivity);
PIX *pixConvertRGBToGrayFast(PIX *pixs);
PIX *pixConvertTo32(PIX *pixs);
void pixDestroy(PIX **ppix);
PIX *pixDrawBoxaRandom(PIX *pixs, BOXA *boxa, l_int32 width);
l_int32 pixGetDepth(const PIX *pix);
l_int32 pixGetHeight(const PIX *pix);
l_ok pixGetRegionsBinary(PIX *pixs, PIX **ppixhm, PIX **ppixtm, PIX **ppixtb, PIXA *pixadb);
l_int32 pixGetWidth(const PIX *pix);
PIX *pixInvert(PIX *pixd, PIX *pixs);
PIX *pixMultiplyByColor(PIX *pixd, PIX *pixs, BOX *box, l_uint32 color);
BOXA *pixSplitIntoBoxa(PIX *pixs, l_int32 minsum, l_int32 skipdist, l_int32 delta, l_int32 maxbg, l_int32 maxcomps, l_int32 remainder);
PIX *pixThresholdToBinary(PIX *pixs, l_int32 thresh);
l_ok pixWriteMemPng(l_uint8 **pfiledata, size_t *pfilesize, PIX *pix, l_float32 gamma);
l_ok pixWritePng(const char *filename, PIX *pix, l_float32 gamma);
]]
