// Needs inkview.h encompassing full 4.x-6.x API
// https://github.com/ezdiy/pocketbook-sdk5/blob/master/arm-obreey-linux-gnueabi/sysroot/usr/local/include/inkview.h
// ~/ffi-cdecl/ffi-cdecl arm-buildroot-linux-musleabihf-gcc inkview_decl.c inkview_h.lua && sed -i 's/char data\[\];/char data[0];/' inkview_h.lua

#include "inkview.h"
#include "inkinternal.h"
#include "ffi-cdecl.h"

cdecl_const(MSG_REBOOT)

cdecl_const(EVT_INIT)
cdecl_const(EVT_EXIT)
cdecl_const(EVT_SHOW)
cdecl_const(EVT_HIDE)
cdecl_const(EVT_KEYPRESS)
cdecl_const(EVT_KEYPRESS_EXT)
cdecl_const(EVT_KEYRELEASE)
cdecl_const(EVT_KEYRELEASE_EXT)
cdecl_const(EVT_KEYREPEAT)
cdecl_const(EVT_KEYREPEAT_EXT)
cdecl_const(EVT_POINTERUP)
cdecl_const(EVT_POINTERDOWN)
cdecl_const(EVT_POINTERMOVE)
cdecl_const(EVT_ORIENTATION)
cdecl_const(EVT_MTSYNC)
cdecl_const(EVT_FOREGROUND)
cdecl_const(EVT_BACKGROUND)

cdecl_const(IV_KEY_POWER)
cdecl_const(IV_KEY_DELETE)
cdecl_const(IV_KEY_OK)
cdecl_const(IV_KEY_UP)
cdecl_const(IV_KEY_DOWN)
cdecl_const(IV_KEY_LEFT)
cdecl_const(IV_KEY_RIGHT)
cdecl_const(IV_KEY_MINUS)
cdecl_const(IV_KEY_PLUS)
cdecl_const(IV_KEY_MENU)
cdecl_const(IV_KEY_PREV)
cdecl_const(IV_KEY_NEXT)
cdecl_const(IV_KEY_HOME)
cdecl_const(IV_KEY_BACK)
cdecl_const(IV_KEY_PREV2)
cdecl_const(IV_KEY_NEXT2)
cdecl_const(IV_KEY_MUSIC)
cdecl_const(IV_KEY_COVEROPEN)
cdecl_const(IV_KEY_COVERCLOSE)
cdecl_const(IV_KEY_ZOOMOUT)
cdecl_const(IV_KEY_ZOOMIN)
cdecl_const(IV_KEY_MENU_POWER)
cdecl_const(IV_KEY_MAX)
cdecl_const(IV_KEY_SHIFT)
cdecl_const(IV_KEY_LANGUAGECHANGE)
cdecl_const(IV_KEY_KEYBOARDCLOSE)
cdecl_const(IV_KEY_0)
cdecl_const(IV_KEY_1)
cdecl_const(IV_KEY_2)
cdecl_const(IV_KEY_3)
cdecl_const(IV_KEY_4)
cdecl_const(IV_KEY_5)
cdecl_const(IV_KEY_6)
cdecl_const(IV_KEY_7)
cdecl_const(IV_KEY_8)
cdecl_const(IV_KEY_9)

cdecl_const(NET_CONNECTED)
cdecl_const(NET_OK)

cdecl_const(REQ_KEYLOCK)

cdecl_enum(input_dev_e)
cdecl_struct(hw_event_data_common_s)
cdecl_type(hw_event_data_common)
cdecl_struct(hw_event_data_pointer_s)
cdecl_type(hw_event_data_pointer)
cdecl_struct(hw_event_s)
cdecl_type(hw_event)

cdecl_struct(icanvas_s)
cdecl_type(icanvas)

cdecl_type(iv_handler)
cdecl_type(iv_mtinfo)

cdecl_type(PANEL_FLAGS)

cdecl_func(ClearOnExit)
cdecl_func(DynamicUpdate)
cdecl_func(FullUpdate)
cdecl_func(FullUpdateHQ)
cdecl_func(GetBatteryPower)
cdecl_func(GetCurrentProfile)
cdecl_func(GetCurrentTask)
cdecl_func(GetDeviceModel)
cdecl_func(GetFrontlightColor)
cdecl_func(GetFrontlightEnabled)
cdecl_func(GetFrontlightState)
cdecl_func(GetSleepmode)
cdecl_func(GetSoftwareVersion)
cdecl_func(GetTaskFramebuffer)
cdecl_func(GetTouchInfoI)
cdecl_func(GoSleep)
cdecl_func(IsCharging)
cdecl_func(IsTaskActive)
cdecl_func(MultitaskingSupported)
cdecl_func(NetConnect)
cdecl_func(NetDisconnect)
cdecl_func(NetMgrPing)
cdecl_func(OpenBook)
cdecl_func(OpenScreen)
cdecl_func(PartialUpdate)
cdecl_func(PartialUpdateHQ)
cdecl_func(PowerOff)
cdecl_func(PrepareForLoop)
cdecl_func(ProcessEventLoop)
cdecl_func(QueryGSensor)
cdecl_func(QueryNetwork)
cdecl_func(SendGlobalRequest)
cdecl_func(SetFrontlightColor)
cdecl_func(SetFrontlightEnabled)
cdecl_func(SetFrontlightState)
cdecl_func(SetPanelType)
cdecl_func(SetSubtaskInfo)
cdecl_func(WaitForUpdateComplete)
cdecl_func(WiFiPower)
cdecl_func(adjustAreaDefault)
cdecl_func(hw_close)
cdecl_func(hw_get_keylock)
cdecl_func(hw_init)
cdecl_func(iv_ipc_request)
cdecl_func(iv_setup_gsensor)
cdecl_func(iv_setup_touchpanel)
cdecl_func(iv_sleepmode)
cdecl_func(iv_update_orientation)
