#include <lodepng.h>

#include "ffi-cdecl.h"

cdecl_enum(LodePNGColorType)
cdecl_type(LodePNGColorType)
cdecl_type(LodePNGDecompressSettings)
cdecl_struct(LodePNGDecompressSettings)
cdecl_struct(LodePNGDecoderSettings)
cdecl_type(LodePNGDecoderSettings)
cdecl_enum(LodePNGFilterStrategy)
cdecl_type(LodePNGFilterStrategy)
cdecl_type(LodePNGCompressSettings)
cdecl_struct(LodePNGCompressSettings)
cdecl_struct(LodePNGEncoderSettings)
cdecl_type(LodePNGEncoderSettings)
cdecl_struct(LodePNGColorMode)
cdecl_type(LodePNGColorMode)
cdecl_struct(LodePNGTime)
cdecl_type(LodePNGTime)
cdecl_struct(LodePNGInfo)
cdecl_type(LodePNGInfo)
cdecl_struct(LodePNGState)
cdecl_type(LodePNGState)
cdecl_func(lodepng_error_text)
cdecl_func(lodepng_decode32_file)
cdecl_func(lodepng_decode32)
cdecl_func(lodepng_decode24_file)
cdecl_func(lodepng_decode24)
cdecl_func(lodepng_decode_memory)
cdecl_func(lodepng_decode_file)
cdecl_func(lodepng_encode32_file)
cdecl_func(lodepng_encode_file)
cdecl_func(lodepng_state_init)
cdecl_func(lodepng_state_cleanup)
cdecl_func(lodepng_state_copy)
cdecl_func(lodepng_decode)
cdecl_func(lodepng_inspect)
cdecl_func(lodepng_encode)
