#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include "ffi-cdecl.h"

cdecl_c99_type(Uint64, uint64_t)
cdecl_c99_type(Sint64, int64_t)
cdecl_c99_type(Uint32, uint32_t)
cdecl_c99_type(Sint32, int32_t)
cdecl_c99_type(Uint16, uint16_t)
cdecl_c99_type(Sint16, int16_t)
cdecl_c99_type(Uint8, uint8_t)
cdecl_c99_type(Sint8, int8_t)

cdecl_const(SDL_BUTTON_LEFT)
cdecl_const(SDL_BUTTON_RIGHT)

cdecl_const(SDL_INIT_EVENTS)
cdecl_const(SDL_INIT_GAMEPAD)
cdecl_const(SDL_INIT_VIDEO)

cdecl_const(SDL_HAT_CENTERED)
cdecl_const(SDL_HAT_UP)
cdecl_const(SDL_HAT_RIGHT)
cdecl_const(SDL_HAT_DOWN)
cdecl_const(SDL_HAT_LEFT)
cdecl_const(SDL_HAT_RIGHTUP)
cdecl_const(SDL_HAT_RIGHTDOWN)
cdecl_const(SDL_HAT_LEFTUP)
cdecl_const(SDL_HAT_LEFTDOWN)

cdecl_const(SDL_TOUCH_MOUSEID)

cdecl_const(SDL_WINDOWPOS_UNDEFINED)
cdecl_const(SDL_WINDOW_FULLSCREEN)
cdecl_const(SDL_WINDOW_RESIZABLE)
cdecl_const(SDL_WINDOW_HIGH_PIXEL_DENSITY)

cdecl_enum(SDL_EventType)
cdecl_enum(SDL_GamepadButton)
cdecl_enum(SDL_MouseWheelDirection)
cdecl_enum(SDL_PenAxis)
cdecl_enum(SDL_PixelFormat)
cdecl_enum(SDL_PowerState)
cdecl_enum(SDL_Scancode)
cdecl_enum(SDL_TextureAccess)

cdecl_type(SDL_AudioDeviceID)
cdecl_type(SDL_CameraID)
cdecl_type(SDL_DisplayID)
cdecl_type(SDL_DisplayModeData)
cdecl_type(SDL_EventType)
cdecl_type(SDL_FRect)
cdecl_type(SDL_Finger)
cdecl_type(SDL_FingerID)
cdecl_type(SDL_Gamepad)
cdecl_type(SDL_JoystickID)
cdecl_type(SDL_KeyboardID)
cdecl_type(SDL_Keycode)
cdecl_type(SDL_Keymod)
cdecl_type(SDL_MouseButtonFlags)
cdecl_type(SDL_MouseID)
cdecl_type(SDL_MouseWheelDirection)
cdecl_type(SDL_PenAxis)
cdecl_type(SDL_PenID)
cdecl_type(SDL_PenInputFlags)
cdecl_type(SDL_PixelFormat)
cdecl_type(SDL_PowerState)
cdecl_type(SDL_Rect)
cdecl_type(SDL_Renderer)
cdecl_type(SDL_Scancode)
cdecl_type(SDL_SensorID)
cdecl_type(SDL_Surface)
cdecl_type(SDL_Texture)
cdecl_type(SDL_TextureAccess)
cdecl_type(SDL_TouchID)
cdecl_type(SDL_Window)
cdecl_type(SDL_WindowID)

cdecl_struct(SDL_Finger)
cdecl_struct(SDL_Rect)

cdecl_func(SDL_StartTextInput)
cdecl_func(SDL_StopTextInput)

cdecl_struct(SDL_CommonEvent)
cdecl_type(SDL_CommonEvent)
cdecl_struct(SDL_DisplayEvent)
cdecl_type(SDL_DisplayEvent)
cdecl_struct(SDL_WindowEvent)
cdecl_type(SDL_WindowEvent)
cdecl_struct(SDL_KeyboardDeviceEvent)
cdecl_type(SDL_KeyboardDeviceEvent)
cdecl_struct(SDL_KeyboardEvent)
cdecl_type(SDL_KeyboardEvent)
cdecl_struct(SDL_TextEditingEvent)
cdecl_type(SDL_TextEditingEvent)
cdecl_struct(SDL_TextEditingCandidatesEvent)
cdecl_type(SDL_TextEditingCandidatesEvent)
cdecl_struct(SDL_TextInputEvent)
cdecl_type(SDL_TextInputEvent)
cdecl_struct(SDL_MouseDeviceEvent)
cdecl_type(SDL_MouseDeviceEvent)
cdecl_struct(SDL_MouseMotionEvent)
cdecl_type(SDL_MouseMotionEvent)
cdecl_struct(SDL_MouseButtonEvent)
cdecl_type(SDL_MouseButtonEvent)
cdecl_struct(SDL_MouseWheelEvent)
cdecl_type(SDL_MouseWheelEvent)
cdecl_struct(SDL_JoyDeviceEvent)
cdecl_type(SDL_JoyDeviceEvent)
cdecl_struct(SDL_JoyAxisEvent)
cdecl_type(SDL_JoyAxisEvent)
cdecl_struct(SDL_JoyBallEvent)
cdecl_type(SDL_JoyBallEvent)
cdecl_struct(SDL_JoyHatEvent)
cdecl_type(SDL_JoyHatEvent)
cdecl_struct(SDL_JoyButtonEvent)
cdecl_type(SDL_JoyButtonEvent)
cdecl_struct(SDL_JoyBatteryEvent)
cdecl_type(SDL_JoyBatteryEvent)
cdecl_struct(SDL_GamepadDeviceEvent)
cdecl_type(SDL_GamepadDeviceEvent)
cdecl_struct(SDL_GamepadAxisEvent)
cdecl_type(SDL_GamepadAxisEvent)
cdecl_struct(SDL_GamepadButtonEvent)
cdecl_type(SDL_GamepadButtonEvent)
cdecl_struct(SDL_GamepadTouchpadEvent)
cdecl_type(SDL_GamepadTouchpadEvent)
cdecl_struct(SDL_GamepadSensorEvent)
cdecl_type(SDL_GamepadSensorEvent)
cdecl_struct(SDL_AudioDeviceEvent)
cdecl_type(SDL_AudioDeviceEvent)
cdecl_struct(SDL_CameraDeviceEvent)
cdecl_type(SDL_CameraDeviceEvent)
cdecl_struct(SDL_SensorEvent)
cdecl_type(SDL_SensorEvent)
cdecl_struct(SDL_QuitEvent)
cdecl_type(SDL_QuitEvent)
cdecl_struct(SDL_UserEvent)
cdecl_type(SDL_UserEvent)
cdecl_struct(SDL_TouchFingerEvent)
cdecl_type(SDL_TouchFingerEvent)
cdecl_struct(SDL_PenProximityEvent)
cdecl_type(SDL_PenProximityEvent)
cdecl_struct(SDL_PenTouchEvent)
cdecl_type(SDL_PenTouchEvent)
cdecl_struct(SDL_PenMotionEvent)
cdecl_type(SDL_PenMotionEvent)
cdecl_struct(SDL_PenButtonEvent)
cdecl_type(SDL_PenButtonEvent)
cdecl_struct(SDL_PenAxisEvent)
cdecl_type(SDL_PenAxisEvent)
cdecl_struct(SDL_PinchFingerEvent)
cdecl_type(SDL_PinchFingerEvent)
cdecl_struct(SDL_RenderEvent)
cdecl_type(SDL_RenderEvent)
cdecl_struct(SDL_DropEvent)
cdecl_type(SDL_DropEvent)
cdecl_struct(SDL_ClipboardEvent)
cdecl_type(SDL_ClipboardEvent)
cdecl_union(SDL_Event)
cdecl_type(SDL_Event)

cdecl_func(SDL_CreateRenderer)
cdecl_func(SDL_CreateTexture)
cdecl_func(SDL_CreateWindow)
cdecl_func(SDL_DestroyRenderer)
cdecl_func(SDL_DestroyTexture)
cdecl_func(SDL_EnableScreenSaver)
cdecl_func(SDL_GetCurrentRenderOutputSize)
cdecl_func(SDL_GetWindowSize)
cdecl_func(SDL_Init)
cdecl_func(SDL_Quit)
cdecl_func(SDL_RenderClear)
cdecl_func(SDL_RenderPresent)
cdecl_func(SDL_RenderTexture)
cdecl_func(SDL_SetMainReady)
cdecl_func(SDL_SetWindowPosition)
cdecl_func(SDL_SetWindowTitle)
cdecl_func(SDL_UpdateTexture)
cdecl_func(SDL_WaitEventTimeout)
cdecl_func(SDL_WasInit)

cdecl_struct(SDL_DisplayMode)
cdecl_type(SDL_DisplayMode)
cdecl_func(SDL_GetPrimaryDisplay)
cdecl_func(SDL_GetCurrentDisplayMode)

cdecl_func(SDL_CreateSurfaceFrom)
cdecl_func(SDL_SetWindowIcon)
cdecl_func(SDL_DestroySurface)
cdecl_func(SDL_SetWindowFullscreen)
cdecl_func(SDL_SyncWindow)

cdecl_func(SDL_GetBasePath)
cdecl_func(SDL_GetPrefPath)
cdecl_func(SDL_GetPowerInfo)
cdecl_func(SDL_GetPlatform)

cdecl_func(SDL_HasClipboardText)
cdecl_func(SDL_GetClipboardText)
cdecl_func(SDL_SetClipboardText)
cdecl_func(SDL_GetError)

cdecl_func(SDL_SetHint)

cdecl_func(SDL_GetJoysticks)
cdecl_func(SDL_IsGamepad)
cdecl_func(SDL_GetGamepadNameForID)
cdecl_func(SDL_OpenGamepad)
cdecl_func(SDL_CloseGamepad)

cdecl_func(SDL_GetTouchFingers)

cdecl_func(SDL_GetVersion)

cdecl_func(SDL_free)
