#include "sqlite3.h"
#include "ffi-cdecl.h"

cdecl_type(sqlite3)
cdecl_type(sqlite3_context)
cdecl_type(sqlite3_stmt)
cdecl_type(sqlite3_value)

cdecl_func(sqlite3_aggregate_context)
cdecl_func(sqlite3_bind_blob)
cdecl_func(sqlite3_bind_double)
cdecl_func(sqlite3_bind_int64)
cdecl_func(sqlite3_bind_null)
cdecl_func(sqlite3_bind_parameter_index)
cdecl_func(sqlite3_bind_text)
cdecl_func(sqlite3_busy_timeout)
cdecl_func(sqlite3_clear_bindings)
cdecl_func(sqlite3_close_v2)
cdecl_func(sqlite3_column_blob)
cdecl_func(sqlite3_column_bytes)
cdecl_func(sqlite3_column_count)
cdecl_func(sqlite3_column_double)
cdecl_func(sqlite3_column_int64)
cdecl_func(sqlite3_column_name)
cdecl_func(sqlite3_column_text)
cdecl_func(sqlite3_column_type)
cdecl_func(sqlite3_create_function)
cdecl_func(sqlite3_errmsg)
cdecl_func(sqlite3_exec)
cdecl_func(sqlite3_finalize)
cdecl_func(sqlite3_open_v2)
cdecl_func(sqlite3_prepare_v2)
cdecl_func(sqlite3_reset)
cdecl_func(sqlite3_result_blob)
cdecl_func(sqlite3_result_double)
cdecl_func(sqlite3_result_error)
cdecl_func(sqlite3_result_int64)
cdecl_func(sqlite3_result_text)
cdecl_func(sqlite3_step)
cdecl_func(sqlite3_value_blob)
cdecl_func(sqlite3_value_bytes)
cdecl_func(sqlite3_value_double)
cdecl_func(sqlite3_value_int64)
cdecl_func(sqlite3_value_text)
cdecl_func(sqlite3_value_type)
