// CPPFLAGS="-I../koreader-base/thirdparty/zyre/zyre/include -I../koreader-base/thirdparty/libzmq/libzmq/include -I../koreader-base/thirdparty/czmq/czmq/include -I../koreader-base/thirdparty/filemq/filemq/include" ./ffi-cdecl ...
#include <zyre.h>
#include <zre_msg.h>
#include <zmq.h>
#include <czmq.h>
#include <fmq.h>

#include "ffi-cdecl.h"

cdecl_type(zctx_t)
cdecl_type(zmsg_t)
cdecl_type(zhash_t)
cdecl_type(zsock_t)
cdecl_type(zframe_t)
cdecl_type(zpoller_t)
//cdecl_type(zsocket_t)
cdecl_type(zyre_t)
cdecl_type(zre_msg_t)
cdecl_type(zyre_event_t)

cdecl_type(zyre_event_type_t)
//cdecl_type(zmq_socket_type_t)
//cdecl_type(zmq_socket_option_t)

cdecl_func(zyre_new)
cdecl_func(zyre_destroy)
cdecl_func(zyre_uuid)
cdecl_func(zyre_name)
cdecl_func(zyre_set_name)
cdecl_func(zyre_set_header)
cdecl_func(zyre_set_verbose)
cdecl_func(zyre_set_port)
cdecl_func(zyre_set_interval)
cdecl_func(zyre_set_interface)
cdecl_func(zyre_start)
cdecl_func(zyre_stop)
cdecl_func(zyre_join)
cdecl_func(zyre_leave)
cdecl_func(zyre_recv)
cdecl_func(zyre_whisper)
cdecl_func(zyre_shout)
cdecl_func(zyre_whispers)
cdecl_func(zyre_shouts)
cdecl_func(zyre_socket)
cdecl_func(zyre_dump)
cdecl_func(zyre_event_new)
cdecl_func(zyre_event_destroy)
cdecl_func(zyre_event_type)
cdecl_func(zyre_event_sender)
cdecl_func(zyre_event_name)
cdecl_func(zyre_event_address)
cdecl_func(zyre_event_header)
cdecl_func(zyre_event_group)

cdecl_func(zmq_getsockopt)

cdecl_func(zctx_new)
cdecl_func(zctx_destroy)
cdecl_func(zsocket_new)
cdecl_func(zsocket_connect)
cdecl_func(zsocket_set_identity)
cdecl_func(zsocket_identity)
cdecl_func(zsocket_destroy)
cdecl_func(zframe_recv)
cdecl_func(zframe_size)
cdecl_func(zframe_data)

cdecl_func(zmsg_new)
cdecl_func(zmsg_size)
cdecl_func(zmsg_addmem)
cdecl_func(zmsg_send)
cdecl_func(zmsg_popstr)
cdecl_func(zstr_free)
cdecl_func(zmsg_pop)
cdecl_func(zhash_unpack)
cdecl_func(zhash_first)
cdecl_func(zhash_next)
cdecl_func(zhash_cursor)
cdecl_func(zhash_lookup)
cdecl_func(zmsg_destroy)
cdecl_func(zhash_destroy)
cdecl_func(zframe_destroy)

cdecl_func(zpoller_new)
cdecl_func(zpoller_destroy)
cdecl_func(zpoller_add)
cdecl_func(zpoller_wait)
cdecl_func(zpoller_expired)
cdecl_func(zpoller_terminated)

cdecl_type(fmq_server_t)
cdecl_type(fmq_client_t)

cdecl_func(fmq_server_new)
cdecl_func(fmq_server_destroy)
cdecl_func(fmq_server_configure)
cdecl_func(fmq_server_setoption)
cdecl_func(fmq_server_bind)
//cdecl_func(fmq_server_recv)
cdecl_func(fmq_server_publish)
cdecl_func(fmq_server_set_anonymous)

cdecl_func(fmq_client_new)
cdecl_func(fmq_client_destroy)
cdecl_func(fmq_client_configure)
cdecl_func(fmq_client_setoption)
cdecl_func(fmq_client_connect)
cdecl_func(fmq_client_recv)
cdecl_func(fmq_client_handle)
cdecl_func(fmq_client_subscribe)
cdecl_func(fmq_client_set_inbox)
cdecl_func(fmq_client_set_resync)
