#include "stub.h"
STUB(ClearTimer)
STUB(GetCurrentTask)
STUB(GetTouchInfo)
STUB(InkViewMain)
STUB(LeaveInkViewMain)
STUB(SendEventTo)
STUB(SetHardTimer)
STUB(SetPanelType)
STUB(SetWeakTimer)
STUB(iv_sleepmode)
